### ISSUE TITLE
Umbraco Cloud Support

### ISSUE THREAD

**Issue by kows** [callumbwhyte/meganav#25]
The editor seems to be working fine but there is a small issue.
When transferring content from one environment to another the configuration is still there but all the internal links are mapped to the wrong nodes.

Discussed on Slack and Udi as a default should fix this.

**Comment by ronaldbarendse** [comment]
Using UDIs instead of IDs would indeed make this editor work with Umbraco Deploy (the actual engine that is used for content transfers on Umbraco Cloud). The other fix is to use a deploy connector; I've just created a PR for this on the Umbraco.Deploy.Contrib package: https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/25

**Comment by ronaldbarendse** [comment]
My PR for the `Umbraco.Deploy.Contrib` package just got merged, so updating to version 1.0.37 adds Umbraco Deploy/Cloud support for Meganav 🎉

**Comment by callumbwhyte** [comment]
Meganav V2 & V3 uses UDIs exclusively, so this should no longer be an issue 🥳
