### ISSUE TITLE
Not showing up in installed packages

### ISSUE THREAD

**Issue by JHUMikeSchnell** [callumbwhyte/meganav#58]
We have installed Meganav into our Umbraco solution via Nuget, and can see the control under the picker, but it is not showing up as an installed package.  Is this normal?

**Comment by callumbwhyte** [comment]
Hey @JHUMikeSchnell,

Thanks for using Meganav!

I started a [discussion on Twitter](https://twitter.com/callumbwhyte/status/1519790366593110019) relating to this issue that caused a bit of debate. It turns out this is intentional by Umbraco - only packages with backoffice settings or database migrations to run will appear. We agreed however that this was a little confusing for users and so I have raised a [pull request](https://github.com/umbraco/Umbraco-CMS/pull/12322) to fix it in Umbraco V10.

This isn't something we can fix in Meganav, and the package has everything it will need to work when my PR is released hopefully in V10.

Hopefully that helps!

Cheers,
Callum
